language: node_js
node_js:
- "0.10"
- "0.12"
- "4"
- "5"
- "6"
- "7"
sudo: false
script: istanbul cover node_modules/.bin/_mocha
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
