environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 14

platform:
  - x86
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
